INSERT INTO dispositivo_validacion (tipo, descripcion) VALUES
('torniquete', 'Non iste molestias perferendis.'),
('torniquete', 'Consectetur vitae placeat nemo saepe dignissimos rem omnis.'),
('sensor biométrico', 'Iusto nisi voluptatum vero.'),
('lector QR', 'Rerum dolor aperiam dolorum iure iusto ratione.'),
('validador móvil', 'Fugit hic culpa ullam doloremque.'),
('terminal fija', 'Perferendis asperiores hic ipsum facilis aspernatur animi vitae.'),
('torniquete', 'Eos eos eaque tenetur voluptatibus cumque corrupti dolores.'),
('validador móvil', 'Facere natus sapiente amet.'),
('torniquete', 'Vel dolore vitae debitis vitae ipsa illo.'),
('lector QR', 'Et doloribus similique quas laborum.'),
('sensor biométrico', 'Esse accusantium aperiam a.'),
('torniquete', 'Molestiae neque minima blanditiis vero et voluptatibus velit.'),
('torniquete', 'Molestias rerum eos ex.'),
('torniquete', 'Reiciendis rem similique animi neque dolorem.'),
('terminal fija', 'Quam odit harum eum magni praesentium.'),
('torniquete', 'Commodi quae dolores aliquid.'),
('torniquete', 'Dolor officia eaque magnam.'),
('validador móvil', 'Inventore error rem animi.'),
('terminal fija', 'Quo voluptates veniam itaque tempora porro.'),
('validador móvil', 'Omnis rerum rerum nemo quo.'),
('torniquete', 'Cupiditate exercitationem libero.'),
('torniquete', 'Autem sunt animi incidunt et molestiae.'),
('terminal fija', 'Eius aliquid veniam fuga officia.'),
('lector QR', 'Sequi beatae culpa possimus fugiat quaerat.'),
('lector QR', 'Et culpa voluptatum unde reprehenderit quia distinctio consequuntur.'),
('validador móvil', 'Vitae odio tenetur similique pariatur assumenda veniam.'),
('lector QR', 'Quis magni quam ratione harum magnam nostrum.'),
('lector QR', 'Atque iure laboriosam iure sunt nesciunt praesentium.'),
('sensor biométrico', 'Explicabo consequuntur aperiam.'),
('validador móvil', 'Tempora sed aspernatur aut voluptatum eius optio.');
